---
- hosts: local
  name: System Configuration
  become: true
  tags:
    - system
    - config
  tasks:
    - name: systemd journal max usage 50M
      ini_file:
        state: present
        path: /etc/systemd/journald.conf
        mode: 0644
        section: Journal
        option: SystemMaxUse
        value: 50M
        no_extra_spaces: yes
      notify: restart systemd-journald

    - name: grub timeout 2s
      ini_file:
        path: /etc/default/grub
        mode: 0644
        section: ''
        option: GRUB_TIMEOUT
        value: '2'
        no_extra_spaces: yes
      notify: grub-mkconfig

    - name: grub load /etc/default/grub.d/*.cfg
      blockinfile:
        path: /etc/default/grub
        mode: 0644
        block: |
          for INCL in /etc/default/grub.d/*.cfg ; do
              source "${INCL}"
          done
      notify: grub-mkconfig

    - name: grub apparmor enabled
      ini_file:
        path: /etc/default/grub.d/apparmor.cfg
        mode: 0644
        section: ''
        option: GRUB_CMDLINE_LINUX_DEFAULT
        value: '"${GRUB_CMDLINE_LINUX_DEFAULT} apparmor=1 lsm=lockdown,yama,apparmor"'
        no_extra_spaces: yes
      notify: grub-mkconfig

    - name: apparmor service enabled
      service:
        name: apparmor
        state: started
        enabled: yes

    - name: faillock deny 12 failed logins
      ini_file:
        path: /etc/security/faillock.conf
        mode: 0644
        section: ''
        option: deny
        value: "12"
        no_extra_spaces: no

    - name: sudo with password for wheel group
      ini_file:
        path: /etc/sudoers
        mode: 0440
        section: ''
        option: '%wheel ALL'
        value: '(ALL) ALL'
        no_extra_spaces: yes
        backup: yes

    - name: ssh socket activation disabled
      ignore_errors: yes
      service:
        name: sshd.socket
        state: stopped
        enabled: no

    - name: ssh daemon enabled and started
      ignore_errors: yes
      service:
        name: sshd
        state: started
        enabled: yes

    - name: service paccache.timer enabled
      ignore_errors: yes
      service:
        name: paccache.timer
        state: started
        enabled: yes

    - name: service pacman-auto-update.timer frequency
      blockinfile:
        path: /etc/systemd/system/pacman-auto-update.timer.d/frequency-24-hours.conf
        block: |
          [Timer]
          OnBootSec=
          OnBootSec=5min
          OnUnitActiveSec=24hour
        create: yes
        group: root
        mode: 0644
        owner: root
      notify: reload systemd daemon

    - name: service pacman-auto-update.timer enabled
      ignore_errors: yes
      service:
        name: pacman-auto-update.timer
        state: started
        enabled: yes

    - name: udev rules for U2F security keys like YubiKey
      copy:
        src: "69-u2f-security-key.local.rules"
        dest: "/etc/udev/rules.d/69-u2f-security-key.local.rules"
        mode: 0644
        owner: root
        group: root
      notify: reload udev

    - name: systemd-resolved enabled
      ignore_errors: yes
      service:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: local repository aur-quatauta
      ini_file:
        path: /etc/pacman.conf
        mode: 0644
        section: 'quatauta'
        option: 'Server'
        value: 'file:///home/daniel/Documents/workspace/aur-$repo/repo'
        no_extra_spaces: no

    - name: repository archzfs
      ini_file:
        path: /etc/pacman.conf
        mode: 0644
        section: 'archzfs'
        option: 'Server'
        value: 'https://archzfs.com/$repo/x86_64/'
        no_extra_spaces: no

    - name: repository archzfs-kernels
      ini_file:
        path: /etc/pacman.conf
        mode: 0644
        section: 'archzfs-kernels'
        option: 'Server'
        value: 'https://end.re/$repo/'
        no_extra_spaces: no

    - name: TLP power saving AC power management
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'RUNTIME_PM_ON_AC'
        value: 'auto'
        no_extra_spaces: yes

    - name: TLP power saving AC SATA link
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SATA_LINKPWR_ON_AC'
        value: '"med_power_with_dipm max_performance"'
        no_extra_spaces: yes

    - name: TLP power saving Battery SATA link
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SATA_LINKPWR_ON_BAT'
        value: '"med_power_with_dipm max_performance"'
        no_extra_spaces: yes

    - name: TLP power saving AC CPU
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SCHED_POWERSAVE_ON_AC'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving AC sound
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SOUND_POWER_SAVE_ON_AC'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving No USB autosuspend on shutdown
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving service
      ignore_errors: yes
      service:
        name: tlp
        state: started
        enabled: yes

    - name: mlocate updatedb timer
      ignore_errors: yes
      service:
        name: updatedb.timer
        state: started
        enabled: yes

    - name: systemd-resolved service
      ignore_errors: yes
      service:
        name: systemd-resolved
        state: started
        enabled: yes

    - name: systemd-resolved service
      ignore_errors: yes
      service:
        name: NetworkManager
        state: started
        enabled: yes

    - name: systemd-timesyncd service
      ignore_errors: yes
      service:
        name: systemd-timesyncd
        state: started
        enabled: yes

    - name: atop service
      ignore_errors: yes
      service:
        name: atop
        state: stopped
        enabled: no

    - name: atopacct service
      ignore_errors: yes
      service:
        name: atopacct
        state: stopped
        enabled: no

    - name: fstrim timer
      ignore_errors: yes
      service:
        name: fstrim.timer
        state: started
        enabled: yes

    - name: gpm service
      ignore_errors: yes
      service:
        name: gpm
        state: started
        enabled: yes

    - name: reflector timer
      ignore_errors: yes
      service:
        name: reflector.timer
        state: started
        enabled: yes

    - name: smartd service
      ignore_errors: yes
      service:
        name: smartd
        state: started
        enabled: yes

    - name: tmpfile for minimum hibernate image size
      blockinfile:
        path: /etc/tmpfiles.d/hibernate-image-size-minimum.conf
        block: |
          # Path                  Mode UID GID Age Argument
          w /sys/power/image_size -    -   -   -   0
        create: yes
        group: root
        mode: 0644
        owner: root

    - name: mkinitcpio hooks
      ini_file:
        path: /etc/mkinitcpio.conf
        mode: 0644
        section: ""
        option: "HOOKS"
        value: "(base udev autodetect modconf block keyboard zfs filesystems resume fsck)"
        no_extra_spaces: yes
      notify: mkinitcpio

    - name: shell aliases
      blockinfile:
        path: /etc/profile.d/alias.local.sh
        block: |
          [ -x "$(command -v dircolors)" ] && eval $(dircolors)
          export LS_OPTIONS="--color=auto -hpv"
          alias ls="ls ${LS_OPTIONS}"
          alias ll="ls -l"
          alias la="ls -A"
          alias lla="ls -lA"
          alias cp="cp -i"
          alias mv="mv -i"
          alias rm="rm -i"
          alias less="less -MNS"
          alias o="less"
        create: yes
        group: root
        mode: 0644
        owner: root

    - name: gdm config night-light
      become_user: gdm
      ignore_errors: true
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/color night-light-enabled"
        value: "true"
        state: present

  handlers:
    - name: restart systemd-journald
      service:
        name: systemd-journald
        state: restarted

    - name: grub-mkconfig
      command: grub-mkconfig -o /boot/grub/grub.cfg

    - name: reload udev
      command: udevadm control --reload

    - name: mkinitcpio
      command: mkinitcpio -P

    - name: reload systemd daemon
      systemd:
        daemon-reload: yes
