---
- hosts: local
  name: System Configuration
  become: true
  tags:
    - system
    - config
  tasks:
    - name: systemd journal max usage 50M
      ini_file:
        state: present
        path: /etc/systemd/journald.conf
        mode: 0644
        section: Journal
        option: SystemMaxUse
        value: 50M
        no_extra_spaces: yes
      notify: systemd journald restart

    - name: grub timeout 2s
      ini_file:
        path: /etc/default/grub
        mode: 0644
        section: ''
        option: GRUB_TIMEOUT
        value: '2'
        no_extra_spaces: yes
      notify: grub-mkconfig

    - name: grub load /etc/default/grub.d/*.cfg
      blockinfile:
        path: /etc/default/grub
        mode: 0644
        block: |
          for INCL in /etc/default/grub.d/*.cfg ; do
              source "${INCL}"
          done
      notify: grub-mkconfig

    - name: grub apparmor enabled
      ini_file:
        path: /etc/default/grub.d/apparmor.cfg
        mode: 0644
        section: ''
        option: GRUB_CMDLINE_LINUX_DEFAULT
        value: '"${GRUB_CMDLINE_LINUX_DEFAULT} apparmor=1 lsm=lockdown,yama,apparmor"'
        no_extra_spaces: yes
      notify: grub-mkconfig

    - name: apparmor service enabled
      service:
        name: apparmor
        state: started
        enabled: yes

    - name: faillock deny 12 failed logins
      ini_file:
        path: /etc/security/faillock.conf
        mode: 0644
        section: ''
        option: deny
        value: "12"
        no_extra_spaces: no

    - name: sudo with password for wheel group
      ini_file:
        path: /etc/sudoers
        mode: 0440
        section: ''
        option: '%wheel ALL'
        value: '(ALL) ALL'
        no_extra_spaces: yes
        backup: yes

    - name: ssh socket activation disabled
      ignore_errors: yes
      service:
        name: sshd.socket
        state: stopped
        enabled: no

    - name: ssh daemon enabled and started
      service:
        name: sshd
        state: started
        enabled: yes

    - name: service paccache.timer enabled
      service:
        name: paccache.timer
        state: started
        enabled: yes

    - name: servie pacman-auto-update.timer enabled
      service:
        name: pacman-auto-update.timer
        state: started
        enabled: yes

    - name: udev rules for U2F security keys like YubiKey
      copy:
        src: "69-u2f-security-key.local.rules"
        dest: "/etc/udev/rules.d/69-u2f-security-key.local.rules"
        mode: 0644
        owner: root
        group: root
      notify: udev reload

    - name: duperemove package installed
      package:
        name: duperemove
        state: present

    - name: duperemove cron job
      copy:
        content: |
          #!/bin/sh

          HASHFILE="/var/lib/duperemove.hash"
          OBJECTS="/bin /boot /etc /home /lib /lib64 /opt /root /sbin /srv /usr /var"

          renice 20 $$    1>/dev/null
          ionice -c3 -p$$ 1>/dev/null
          duperemove -r -d --hashfile="${HASHFILE}" ${OBJECTS} 1>/dev/null
          true
        dest: "/etc/cron.daily/duperemove.sh"
        mode: 0755
        owner: root
        group: root

    - name: systemd-resolved enabled
      service:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: repository archzfs
      ini_file:
        path: /etc/pacman.conf
        mode: 0644
        section: 'archzfs'
        option: 'Server'
        value: 'https://archzfs.com/$repo/x86_64/'
        no_extra_spaces: no

    - name: repository archzfs-kernels
      ini_file:
        path: /etc/pacman.conf
        mode: 0644
        section: 'archzfs-kernels'
        option: 'Server'
        value: 'https://end.re/$repo/'
        no_extra_spaces: no

    - name: TLP power saving AC power management
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'RUNTIME_PM_ON_AC'
        value: 'auto'
        no_extra_spaces: yes

    - name: TLP power saving AC SATA link
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SATA_LINKPWR_ON_AC'
        value: '"med_power_with_dipm max_performance"'
        no_extra_spaces: yes

    - name: TLP power saving Battery SATA link
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SATA_LINKPWR_ON_BAT'
        value: '"med_power_with_dipm max_performance"'
        no_extra_spaces: yes

    - name: TLP power saving AC CPU
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SCHED_POWERSAVE_ON_AC'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving AC sound
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'SOUND_POWER_SAVE_ON_AC'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving No USB autosuspend on shutdown
      ini_file:
        path: /etc/tlp.d/90-local.conf
        mode: 0644
        section: ''
        option: 'USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN'
        value: '1'
        no_extra_spaces: yes

    - name: TLP power saving service
      service:
        name: tlp
        state: started
        enabled: true

  handlers:
    - name: systemd journald restart
      service:
        name: systemd-journald
        state: restarted

    - name: grub-mkconfig
      command: grub-mkconfig -o /boot/grub/grub.cfg

    - name: udev reload
      command: udevadm control --reload
