---
- hosts: local
  name: Packages GUI
  become: true
  tags:
    - system
    - package
    - gui
  tasks:
    - name: GUI packages
      package:
        state: present
        name:
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - awesome-terminal-fonts
          - deepin-community-wallpapers
          - deepin-wallpapers
          - deepin-wallpapers-plasma
          - desktop-file-utils
          - djvulibre
          - gdm
          - gnome-autoar
          - gnome-backgrounds
          - gnome-bluetooth
          - gnome-color-manager
          - gnome-control-center
          - gnome-desktop
          - gnome-session
          - gnome-settings-daemon
          - gnome-shell
          - gnome-shell-extensions
          - gnome-themes-extra
          - gnome-tweaks
          - gvfs
          - gvfs-afc
          - gvfs-gphoto2
          - gvfs-mtp
          - gvfs-smb
          - lightdm
          - lightdm-gtk-greeter
          - light-locker
          - otf-fira-sans
          - plasma-workspace-wallpapers
          - powerline
          - powerline-common
          - powerline-fonts
          - startup-notification
          - sway
          - swaybg
          - swayidle
          - swaylock
          - ttf-croscore
          - ttf-dejavu
          - ttf-fira-code
          - ttf-font-awesome
          - ttf-inconsolata
          - ttf-ionicons
          - ttf-jetbrains-mono
          - ttf-liberation
          - ttf-roboto
          - ttf-roboto-mono
          - unclutter
          - waybar
          - wlroots
          - wmctrl
          - x86_energy_perf_policy
          - xapps
          - xcape
          - xcb-proto
          - xcb-util
          - xcb-util-errors
          - xcb-util-image
          - xcb-util-keysyms
          - xcb-util-renderutil
          - xcb-util-wm
          - xcb-util-xrm
          - xclip
          - xdg-user-dirs
          - xdg-user-dirs-gtk
          - xdg-utils
          - xf86-input-evdev
          - xf86-input-libinput
          - xkeyboard-config
          - xorg-fonts-alias-misc
          - xorg-fonts-encodings
          - xorg-fonts-misc
          - xorg-iceauth
          - xorg-luit
          - xorg-mkfontscale
          - xorgproto
          - xorg-server
          - xorg-server-common
          - xorg-server-xwayland
          - xorg-sessreg
          - xorg-setxkbmap
          - xorg-smproxy
          - xorg-x11perf
          - xorg-xauth
          - xorg-xbacklight
          - xorg-xclipboard
          - xorg-xcmsdb
          - xorg-xcursorgen
          - xorg-xdpyinfo
          - xorg-xdriinfo
          - xorg-xev
          - xorg-xfontsel
          - xorg-xgamma
          - xorg-xhost
          - xorg-xinput
          - xorg-xkbcomp
          - xorg-xkbevd
          - xorg-xkbutils
          - xorg-xkill
          - xorg-xlsatoms
          - xorg-xlsclients
          - xorg-xmodmap
          - xorg-xpr
          - xorg-xprop
          - xorg-xrandr
          - xorg-xrdb
          - xorg-xrefresh
          - xorg-xset
          - xorg-xsetroot
          - xorg-xvinfo
          - xorg-xwd
          - xorg-xwininfo
          - xorg-xwud
          - xterm
          - zbar
