---
- hosts: local
  name: Packages
  become: true
  tags:
    - system
    - package
  tasks:
    - name: System packages
      package:
        state: present
        name:
          - acl
          - acpi
          - alsa-utils
          - apparmor
          - archlinux-keyring
          - atop
          - attr
          - audit
          - base
          - bash
          - bash-completion
          - bc
          - bind
          - bolt
          - bridge-utils
          - btrfs-progs
          - bzip2
          - ca-certificates
          - ca-certificates-mozilla
          - ca-certificates-utils
          - checksec
          - cifs-utils
          - coreutils
          - cracklib
          - cryptsetup
          - curl
          - dconf-editor
          - ddrescue
          - dhclient
          - dhcpcd
          - dmraid
          - dnssec-anchors
          - dosfstools
          - dstat
          - duperemove
          - e2fsprogs
          - efibootmgr
          - efivar
          - elfutils
          - etckeeper
          - ethtool
          - fakeroot
          - file
          - filesystem
          - findutils
          - gawk
          - geoclue
          - geoip
          - geoip-database
          - gnu-netcat
          - gpm
          - gptfdisk
          - grep
          - grub
          - gzip
          - haveged
          - hddtemp
          - hdparm
          - htop
          - hwids
          - hwloc
          - iana-etc
          - inetutils
          - inotify-tools
          - iotop
          - iproute2
          - iptables
          - iputils
          - ipw2100-fw
          - ipw2200-fw
          - iw
          - iwd
          - jemalloc
          - kbd
          - keyutils
          - kmod
          - less
          - linux
          - linux-firmware
          - logrotate
          - lsb-release
          - lshw
          - lsof
          - lvm2
          - man-db
          - man-pages
          - mkinitcpio
          - mkinitcpio-busybox
          - mlocate
          - mosh
          - mtools
          - mtr
          - namcap
          - nano
          - netctl
          - net-tools
          - networkmanager
          - network-manager-applet
          - nginx-mainline
          - ntfs-3g
          - openssh
          - openssl
          - os-prober
          - pacman
          - pacman-contrib
          - pacman-mirrorlist
          - pam
          - pambase
          - parallel
          - parted
          - patch
          - pciutils
          - pinentry
          - powertop
          - procps-ng
          - psmisc
          - pv
          - pwgen
          - recode
          - reflector
          - reiserfsprogs
          - rhash
          - rsync
          - run-parts
          - screen
          - sed
          - shadow
          - smbclient
          - snapper
          - sqlite
          - squashfs-tools
          - strace
          - sudo
          - sysfsutils
          - sysstat
          - systemd
          - systemd-resolvconf
          - tar
          - texinfo
          - time
          - tlp
          - tlp-rdw
          - tmux
          - tmuxp
          - traceroute
          - tree
          - tzdata
          - udisks2
          - unace
          - unrar
          - unzip
          - upower
          - usbmuxd
          - usbutils
          - util-linux
          - wget
          - which
          - wireguard-tools
          - wireless-regdb
          - wireless_tools
          - xfsprogs
          - xxhash
          - xz
          - zenity
          - zip
          - zsh
          - zsh-completions
          - zstd

    - name: GUI packages
      package:
        state: present
        name:
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - awesome-terminal-fonts
          - deepin-community-wallpapers
          - deepin-wallpapers
          - deepin-wallpapers-plasma
          - desktop-file-utils
          - djvulibre
          - gdm
          - gnome-autoar
          - gnome-backgrounds
          - gnome-bluetooth
          - gnome-color-manager
          - gnome-control-center
          - gnome-desktop
          - gnome-session
          - gnome-settings-daemon
          - gnome-shell
          - gnome-shell-extensions
          - gnome-themes-extra
          - gnome-tweaks
          - gvfs
          - gvfs-afc
          - gvfs-gphoto2
          - gvfs-mtp
          - gvfs-smb
          - lightdm
          - lightdm-gtk-greeter
          - light-locker
          - otf-fira-sans
          - plasma-workspace-wallpapers
          - powerline
          - powerline-common
          - powerline-fonts
          - startup-notification
          - sway
          - swaybg
          - swayidle
          - swaylock
          - ttf-croscore
          - ttf-dejavu
          - ttf-fira-code
          - ttf-font-awesome
          - ttf-inconsolata
          - ttf-ionicons
          - ttf-jetbrains-mono
          - ttf-liberation
          - ttf-roboto
          - ttf-roboto-mono
          - unclutter
          - waybar
          - wlroots
          - wmctrl
          - x86_energy_perf_policy
          - xapps
          - xcape
          - xcb-proto
          - xcb-util
          - xcb-util-errors
          - xcb-util-image
          - xcb-util-keysyms
          - xcb-util-renderutil
          - xcb-util-wm
          - xcb-util-xrm
          - xclip
          - xdg-user-dirs
          - xdg-user-dirs-gtk
          - xdg-utils
          - xf86-input-evdev
          - xf86-input-libinput
          - xkeyboard-config
          - xorg-fonts-alias-misc
          - xorg-fonts-encodings
          - xorg-fonts-misc
          - xorg-iceauth
          - xorg-luit
          - xorg-mkfontscale
          - xorgproto
          - xorg-server
          - xorg-server-common
          - xorg-server-xwayland
          - xorg-sessreg
          - xorg-setxkbmap
          - xorg-smproxy
          - xorg-x11perf
          - xorg-xauth
          - xorg-xbacklight
          - xorg-xclipboard
          - xorg-xcmsdb
          - xorg-xcursorgen
          - xorg-xdpyinfo
          - xorg-xdriinfo
          - xorg-xev
          - xorg-xfontsel
          - xorg-xgamma
          - xorg-xhost
          - xorg-xinput
          - xorg-xkbcomp
          - xorg-xkbevd
          - xorg-xkbutils
          - xorg-xkill
          - xorg-xlsatoms
          - xorg-xlsclients
          - xorg-xmodmap
          - xorg-xpr
          - xorg-xprop
          - xorg-xrandr
          - xorg-xrdb
          - xorg-xrefresh
          - xorg-xset
          - xorg-xsetroot
          - xorg-xvinfo
          - xorg-xwd
          - xorg-xwininfo
          - xorg-xwud
          - xterm
          - zbar

    - name: Application packages
      package:
        state: present
        name:
          - android-tools
          - anki
          - ansible
          - ansible-lint
          - aria2
          - asciidoctor
          - asciinema
          - atool
          - bat
          - bmon
          - bubblewrap
          - diffstat
          - diffutils
          - docker
          - docker-compose
          - elixir
          - emacs
          - evince
          - exa
          - exiv2
          - feh
          - file-roller
          - firefox
          - gcolor2
          - geeqie
          - ghostscript
          - gimp
          - git
          - gitlab-runner
          - gnupg
          - gpgme
          - gramps
          - grc
          - grim
          - gucharmap
          - gvim
          - hspell
          - hunspell
          - hunspell-de
          - hunspell-en_GB
          - hunspell-en_US
          - hyphen
          - hyphen-de
          - hyphen-en
          - id3v2
          - jpegoptim
          - ldb
          - lensfun
          - liferea
          - light
          - lmdb
          - lrzip
          - lxmenu-data
          - lxterminal
          - mailcap
          - mako
          - mediainfo
          - meld
          - mpg123
          - mpv
          - msmtp
          - ncdu
          - neomutt
          - nmap
          - nm-connection-editor
          - nmon
          - notmuch
          - notmuch-mutt
          - noto-fonts
          - numlockx
          - offlineimap
          - opera
          - paperkey
          - pcmanfm
          - qalculate-gtk
          - qrencode
          - quodlibet
          - radicale
          - rdesktop
          - ripgrep
          - rofi
          - rsnapshot
          - ruby
          - ruby-bundler
          - rubygems
          - ruby-rake
          - signal-desktop
          - tidy
          - urlscan
          - v4l-utils
          - vdirsyncer
          - vim-ansible
          - vim-fugitive
          - virtualbox
          - virtualbox-guest-iso
          - virtualbox-host-modules-arch
          - vorbisgain
          - vorbis-tools
          - xca
          - yamllint
          - youtube-dl

    - name: LaTeX packages
      package:
        state: present
        name:
          - biber
          - texlive-bibtexextra
          - texlive-bin
          - texlive-core
          - texlive-fontsextra
          # texlive-formatsextra
          # texlive-games
          - texlive-humanities
          - texlive-langextra
          - texlive-latexextra
          # texlive-music
          # texlive-pictures
          # texlive-pstricks
          # texlive-publishers
          # texlive-science

# pikaur packages:
#
# ansible-completion-git
# asciinema-edit
# aurebuildcheck-git
# autotiling
# bitwarden-bin
# dropbox
# emacs-ansible
# emacs-dash
# emacs-f
# emacs-s
# emacs-yasnippet
# etc-update
# exif
# findbrokenpkgs
# git-extras
# gnome-shell-extension-dash-to-dock
# gnome-shell-extension-easyscreencast
# gnome-shell-extension-topicons-plus
# gnome-shell-extension-tray-icons
# gnome-shell-extension-workspaces-to-dock
# latencytop
# lbdb
# mailcheck
# mmv
# networkmanager-wireguard-git
# nginx-unitd
# nginx-unit-python
# nginx-unit-ruby
# pacman-auto-update
# pacman-updatedb-hook
# paper-icon-theme
# pnmixer
# python-soco
# rcm
# rtl8812au-dkms-git
# ruby-pry
# safecopy
# sedutil
# snapd
# socos
# starship-bin
# sway-alttab-bin
# ttf-menlo-powerline-git
# ttf-meslo
# ttf-roboto-slab
# ttf-symbola
# upd72020x-fw
# urlview
# usbtop
# vim-gnupg
# vim-guicolorscheme
# vim-inkpot-git
# vimix-gtk-themes
# vimix-icon-theme
# vim-rails
# virtualbox-ext-oracle
# waypipe
# wev
# wrk
# xdgmenumaker
# xkblayout
# xkblayout-state-git
# xkbset

# not dell latitute: intel-ucode

# own packages:
# pam_mktemp
# systemrescuecd
# signify-mail
# exercism-cli

- hosts: local
  name: System Configuration
  become: true
  tags:
    - system
    - config
  tasks:
    - name: systemd journal max usage
      ini_file:
        state: present
        path: /etc/systemd/journald.conf
        mode: 0644
        section: Journal
        option: SystemMaxUse
        value: 50M
        no_extra_spaces: yes
      notify: restart systemd journald

    - name: grub timeout 1s
      ini_file:
        path: /etc/default/grub
        mode: 0644
        section: ''
        option: GRUB_TIMEOUT
        value: '1'
        no_extra_spaces: yes

    - name: grub load /etc/default/grub.d/*.cfg
      blockinfile:
        path: /etc/default/grub
        mode: 0644
        block: |
          for INCL in /etc/default/grub.d/*.cfg ; do
              source "${INCL}"
          done
      notify: grub-mkconfig

    - name: grub enable apparmor
      ini_file:
        path: /etc/default/grub.d/apparmor.cfg
        mode: 0644
        section: ''
        option: GRUB_CMDLINE_LINUX_DEFAULT
        value: '"${GRUB_CMDLINE_LINUX_DEFAULT} apparmor=1 lsm=lockdown,yama,apparmor"'
        no_extra_spaces: yes
      notify: grub-mkconfig

  handlers:
    - name: restart systemd journald
      service:
        name: systemd-journald
        state: restarted

    - name: grub-mkconfig
      command: grub-mkconfig -o /boot/grub/grub.cfg
