---
- hosts: local
  name: Packages System
  become: true
  tags:
    - system
    - package
  tasks:
    - name: System packages
      package:
        state: present
        name:
          - acl
          - acpi
          - alsa-utils
          - apparmor
          - archlinux-keyring
          - atop
          - attr
          - audit
          - base
          - base-devel
          - bash
          - bash-completion
          - bc
          - bind
          - bolt
          - bridge-utils
          - btrfs-progs
          - bzip2
          - ca-certificates
          - ca-certificates-mozilla
          - ca-certificates-utils
          - checksec
          - cifs-utils
          - coreutils
          - cracklib
          - cryptsetup
          - curl
          - dconf-editor
          - ddrescue
          - dhclient
          - dhcpcd
          - dmraid
          - dnssec-anchors
          - dosfstools
          - dstat
          - duperemove
          - e2fsprogs
          - efibootmgr
          - efivar
          - elfutils
          - etckeeper
          - ethtool
          - fakeroot
          - file
          - filesystem
          - findutils
          - gawk
          - geoclue
          - geoip
          - geoip-database
          - gnu-netcat
          - gpm
          - gptfdisk
          - grep
          - grub
          - gzip
          - haveged
          - hddtemp
          - hdparm
          - htop
          - hwids
          - hwloc
          - iana-etc
          - inetutils
          - inotify-tools
          - iotop
          - iproute2
          - iptables
          - iputils
          - ipw2100-fw
          - ipw2200-fw
          - iw
          - iwd
          - jemalloc
          - kbd
          - keyutils
          - kmod
          - less
          - linux
          - linux-firmware
          - logrotate
          - lsb-release
          - lshw
          - lsof
          - lvm2
          - man-db
          - man-pages
          - mkinitcpio
          - mkinitcpio-busybox
          - mlocate
          - mosh
          - mtools
          - mtr
          - namcap
          - nano
          - net-tools
          - networkmanager
          - network-manager-applet
          - nginx-mainline
          - ntfs-3g
          - openssh
          - openssl
          - os-prober
          - pacman
          - pacman-contrib
          - pacman-mirrorlist
          - pam
          - pambase
          - parallel
          - parted
          - patch
          - pciutils
          - pinentry
          - powertop
          - procps-ng
          - psmisc
          - pv
          - pwgen
          - recode
          - reflector
          - reiserfsprogs
          - rhash
          - rsync
          - run-parts
          - screen
          - sed
          - shadow
          - smartmontools
          - smbclient
          - sqlite
          - squashfs-tools
          - strace
          - sudo
          - sysfsutils
          - sysstat
          - systemd
          - systemd-resolvconf
          - tar
          - texinfo
          - time
          - tlp
          - tlp-rdw
          - tmux
          - tmuxp
          - traceroute
          - tree
          - tzdata
          - udisks2
          - unace
          - unrar
          - unzip
          - upower
          - usbmuxd
          - usbutils
          - util-linux
          - wget
          - which
          - wireless-regdb
          - wireless_tools
          - xfsprogs
          - xxhash
          - xz
          - zenity
          - zip
          - zsh
          - zsh-completions
          - zstd

# pikaur packages:
#
# ansible-completion-git
# aurebuildcheck-git
# autotiling
# bitwarden-bin
# dropbox
# etc-update
# exif
# findbrokenpkgs
# gnome-shell-extension-dash-to-dock
# gnome-shell-extension-topicons-plus
# gnome-shell-extension-tray-icons
# gnome-shell-extension-workspaces-to-dock
# latencytop
# mmv
# nginx-unitd
# nginx-unit-python
# pacman-auto-update
# pacman-updatedb-hook
# paper-icon-theme
# pnmixer
# rcm
# rtl8812au-dkms-git
# ruby-pry
# safecopy
# snapd
# starship-bin
# ttf-roboto-slab
# ttf-symbola
# upd72020x-fw
# urlview
# usbtop
# vim-gnupg
# vim-guicolorscheme
# vim-inkpot-git
# vimix-gtk-themes
# vimix-icon-theme
# vim-rails
# waypipe
# wev
# wrk
# xdgmenumaker
# xkblayout
# xkblayout-state-git
# xkbset

# not dell latitute: intel-ucode

# own packages:
#
# pam_mktemp
# signify-mail
# exercism-cli
