---
- hosts: local
  name: Packages Applications
  become: true
  tags:
    - system
    - package
    - application
    - apps
  tasks:
    - name: Application packages
      package:
        state: present
        name:
          - ansible
          - ansible-lint
          - aria2
          - atool
          - bat
          - bmon
          - bubblewrap
          - diffstat
          - diffutils
          - docker
          - elixir
          - emacs
          - evince
          - exa
          - exiv2
          - feh
          - file-roller
          - firefox
          - gcolor2
          - geeqie
          - ghostscript
          - gimp
          - git
          - gitlab-runner
          - gnupg
          - gpgme
          - grim
          - gucharmap
          - gvim
          - id3v2
          - jpegoptim
          - liferea
          - light
          - lxterminal
          - mailcap
          - mako
          - mediainfo
          - mpg123
          - mpv
          - msmtp
          - ncdu
          - neomutt
          - nmap
          - nm-connection-editor
          - nmon
          - notmuch
          - notmuch-mutt
          - noto-fonts
          - numlockx
          - offlineimap
          - opera
          - paperkey
          - pcmanfm
          - qalculate-gtk
          - radicale
          - rdesktop
          - ripgrep
          - rofi
          - rsnapshot
          - ruby
          - ruby-bundler
          - rubygems
          - ruby-rake
          - signal-desktop
          - tidy
          - urlscan
          - v4l-utils
          - vdirsyncer
          - vim-ansible
          - vim-fugitive
          - vorbisgain
          - vorbis-tools
          - xca
          - yamllint
          - youtube-dl
