#!/usr/bin/env ansible-playbook
---
- hosts: local
  name: user configuration
  tasks:
  - name: group for user account daniel
    become: true
    group:
      name: daniel
      state: present
      system: no

  - name: gather groups
    getent:
      database: group

  - name: user daniel
    become: true
    user:
      state: present
      name: daniel
      system: no
      comment: Daniel
      groups: daniel
      append: yes
      shell: /usr/bin/zsh
      create_home: true
    register: user_daniel

  - name: user daniel groups
    become: true
    ignore_errors: yes
    user:
      state: present
      name: daniel
      groups: "{{ item }}"
      append: yes
    when: item in ansible_facts.getent_group
    loop:
    - users
    - vboxusers
    - video
    - wheel

  - name: snap hey-mail fontconfig workaround
    file:
      path: "{{ user_daniel.home }}/snap/hey-mail/common/.cache/fontconfig"
      state: file
      group: daniel
      owner: daniel
      mode: 0644
    when: user_daniel.home
