#!/usr/bin/env ansible-playbook
---
- hosts: local
  name: User Configuration
  tasks:
  - name: Group for user account daniel
    become: true
    group:
      name: daniel
      state: present
      system: no

  - name: User account daniel
    become: true
    user:
      state: present
      name: daniel
      system: no
      comment: Daniel
      groups: users,wheel,daniel
      append: yes
      shell: /usr/bin/zsh
      create_home: true

  - name: User account daniel
    become: true
    ignore_errors: yes
    user:
      state: present
      name: daniel
      system: no
      comment: Daniel
      groups: vboxusers
      append: yes
      shell: /usr/bin/zsh
      create_home: true
