#!/usr/bin/env ansible-playbook
---
- hosts: local
  name: user configuration
  tasks:
  - name: group for user account daniel
    become: true
    group:
      name: daniel
      state: present
      system: no

  - name: user daniel
    become: true
    user:
      state: present
      name: daniel
      system: no
      comment: Daniel
      groups: users,wheel,daniel,video
      append: yes
      shell: /usr/bin/zsh
      create_home: true

  - name: user daniel group vboxusers
    become: true
    ignore_errors: yes
    user:
      state: present
      name: daniel
      groups: vboxusers
      append: yes
